# Generated by Django 4.0.3 on 2022-05-15 20:49

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateField(auto_now_add=True, verbose_name='Creado')),
                ('alterado', models.DateField(auto_now=True, verbose_name='Atualizado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
        ),
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=100, verbose_name='Produto')),
                ('imagem', stdimage.models.StdImageField(upload_to='protutos', verbose_name='Imagem')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço')),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Subtotal')),
                ('vendedor', models.CharField(max_length=100, verbose_name='Vendedor')),
                ('total', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Total')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoria')),
                ('imagem', stdimage.models.StdImageField(null=True, upload_to='protutos', verbose_name='Imagem')),
                ('descricao', models.CharField(default='*', max_length=100, verbose_name='Descrição curta')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='produto.base')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço')),
                ('imagem', stdimage.models.StdImageField(null=True, upload_to='protutos', verbose_name='Imagem')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, verbose_name='Slug')),
                ('descricao_curta', models.CharField(max_length=100, verbose_name='Descrição curta')),
                ('descricao_longa', models.TextField(max_length=4000, verbose_name='Descrição longa')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.categoria', verbose_name='Categoria')),
                ('vendedo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vendedor', verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
            bases=('produto.base',),
        ),
        migrations.CreateModel(
            name='MeusCursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Meu Curso',
                'verbose_name_plural': 'Meus Cursos',
            },
        ),
    ]
