# Generated by Django 4.0.3 on 2022-06-29 09:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_alter_categoria_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='meuscursos',
            name='data',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data'),
            preserve_default=False,
        ),
    ]
